Repository holochain/scaffolding, pull requests merged in 2025-02, with the labels that each got.

#453 revert: Revert to serde_yaml
  Cargo.lock
  Cargo.toml
  src/error.rs
  src/scaffold/app.rs
  src/scaffold/app/manifests.rs
  src/scaffold/app/utils.rs
  src/scaffold/dna.rs
  src/scaffold/dna/coordinator.rs
  src/scaffold/dna/integrity.rs
  src/scaffold/dna/manifest.rs
Labels: ShouldBackport/0.4

#457 fix: wrongly used v-if directive
  templates/ui-frameworks/vue/entry-type/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{pascal_case entry_type.name}}Detail.vue.hbs
Labels: ShouldBackport/0.3, ShouldBackport/0.4

#467 Expand merge helper scopes
  src/templates/helpers/merge.rs
Labels: should_backport
